apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  type: LoadBalancer
  selector:
    node: js
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30007 
      targetPort: 3000
        

